### ISSUE TITLE
github workflow action

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/blog#161]
+ 打印变量
```yaml
    - name: console github event
      run: |
        echo "${{ toJSON(github.event.repository)}}"
```
