### ISSUE TITLE
css重构

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/blog#74]
+ 上下拉动滚动条时卡顿、慢
```css
E {
    -webkit-overflow-scrolling: touch;
    overflow-scrolling: touch;
}

//  Android3+和iOS5+支持CSS3的新属性为overflow-scrolling
```

+ 禁止复制、选中文本
```
E {
    -webkit-user-select: none;
    -moz-user-select: none;
    -khtml-user-select: none;
     user-select: none;
}
```

+ 长时间按住页面出现闪退
```
E {
    -webkit-touch-callout: none;
}
```

+ iphone及ipad下输入框默认内阴影
```
E {
    -webkit-appearance: none; 
}
```

+ 更改输入框placeholder的颜色
```
input::-webkit-input-placeholder { color:#999; }
input:focus::-webkit-input-placeholder { color:#333; }

//  placeholder的文字在ios下可以换行，android不行
```

+ ios和android下触摸元素时出现半透明灰色遮罩
```
E {
    -webkit-tap-highlight-color:rgba(255,255,255,0)
}
```

+ 圆角bug
某些Android手机圆角失效
```
background-clip: padding-box;
```

[https://www.xuanfengge.com/mobile-guide-page-refactoring-css-articles.html](https://www.xuanfengge.com/mobile-guide-page-refactoring-css-articles.html)
